### ISSUE TITLE
packages used in `R`/`Rmd` files but not required during configure 

### ISSUE THREAD

**Issue by jonasfreimuth** [BIMSBbioinfo/pigx_sarscov2_ww#110]
* GenomicRanges
* data.table 
* htmltools 
* jsonlite
* knitr
* tidyverse
* viridis

Packages are currently used here: 

```GenomicRanges
scripts/Sample_prep_scripts/sigmuts_on_amplicons.rmd:library(GenomicRanges)

data.table
scripts/report_scripts/index.Rmd:library(data.table)
scripts/generateNavigation.R:library(data.table)

htmltools
scripts/report_scripts/index.Rmd:library(htmltools)

jsonlite
scripts/renderReport.R:library(jsonlite)

knitr
scripts/report_scripts/taxonomic_classification.Rmd:library(knitr)
scripts/report_scripts/variantreport_p_sample.Rmd:library(knitr)

tidyverse
scripts/Sample_prep_scripts/sigmuts_on_amplicons.rmd:library(tidyverse)

viridis
scripts/report_scripts/index.Rmd:library(viridis)```

**Comment by alexg9010** [comment]
Hi Jonas,

The viridis package will be added with merging the PR #100.

Concerning the tidyverse package, I would argue against using it as a dependency, because it is a whole suite of packages where only a fraction are really required. Maybe you are able to cut it down to the bare minimum (i.e. dplyr, magrittr,...).

For the other packages I am totally with you.

Best
Alex

**Comment by rekado** [comment]
I agree about the tidyverse package.  It's just a meta package so this import should be replaced with imports of the concrete packages that are actually used there.

**Comment by jonasfreimuth** [comment]
`data.table` will be added by #121
