### ISSUE TITLE
variant_report: render_variant_report generates CSV files that are not declared as outputs

### ISSUE THREAD

**Issue by rekado** [BIMSBbioinfo/pigx_sarscov2_ww#19]
`render_variant_report` has a side effect the first time it is run.  It generates two CSV files that are used by subsequent report invocations.  This is bad as it results in duplication of work when the reports are generated in parallel, and partially written files may be considered valid inputs.

The correct fix here is to generate these CSV files in a separate rule/script outside of the reports and declare them as inputs to `render_variant_report`.

## Relevant lines: 
everything below: https://github.com/BIMSBbioinfo/pigx_sarscov2_ww/blob/3bf14089ec946afa994e991df15f9ea63bcaa653/scripts/report_scripts/variantreport_p_sample.Rmd#L535 

Code Chunks:   
* [csv_output_variant_plot](https://github.com/BIMSBbioinfo/pigx_sarscov2_ww/blob/3bf14089ec946afa994e991df15f9ea63bcaa653/scripts/report_scripts/variantreport_p_sample.Rmd#L546)  
* [csv_output_mutation_plot](https://github.com/BIMSBbioinfo/pigx_sarscov2_ww/blob/3bf14089ec946afa994e991df15f9ea63bcaa653/scripts/report_scripts/variantreport_p_sample.Rmd#L598)

**Comment by vicfabienne** [comment]
@rekado "and declare them as inputs to render_variant_report." - I think this is a bit misleading. Because the data that goes into that outputs is generated within the report. When thinking ahead (not having so many parts within the reports anymore) - the data for the variant_plot output will be generated by deconvolution scripts, the data for the mutation script by other scripts. 

So then the csv_output files can't really be "input for the report", no? Can you maybe clarify this in case you had anything specific in mind about that already?

**Comment by vicfabienne** [comment]
with the development branch, at least the csv data_mutation_plot is now declared as output. 
Only data_variantplot not yet. Will fix this soon too.

**Comment by rekado** [comment]
It doesn't matter whether the files are generated or provided by the user.  When a script needs certain files they are inputs, and thus must be declared in the workflow.

When inputs are not declared, the workflow engine cannot arrange for them to be present by the time the workflow step runs, which breaks a fundamental assumption.
