### ISSUE TITLE
qc-report: table "Number of amplicons covered" displays numbers incorrect

### ISSUE THREAD

**Issue by mirifax** [BIMSBbioinfo/pigx_sarscov2_ww#49]
![Screenshot from 2021-06-02 12-24-26](https://user-images.githubusercontent.com/45397751/120465928-cc9ca880-c39e-11eb-8b85-e6b0a64de311.png)

**Comment by rekado** [comment]
Could you clarify what's incorrect about the display of the numbers?  Wrong order?

**Comment by al2na** [comment]
yes, clarification needed, also what is the meaning of "invalid" label

**Comment by vicfabienne** [comment]
I think "invalid" is "this doesn't seems right" - which probably goes into the direction of "not a bug or error but a serious issue about the report content" 

The thing I see that would need to be done here is to correct the column and row name

**Comment by mirifax** [comment]
I saw that it changed. But shouldn't it add up to 100? If not, maybe it needs a sentence more explanation. 
! At least it confuses me.
[Screenshot from 2021-06-08 12-00-25](https://user-images.githubusercontent.com/45397751/121166319-432f1f80-c851-11eb-904c-c4bab36b9b82.png)

**Comment by vicfabienne** [comment]
Where does this screenshot come from? From which sample? 
and no, it shouldn't add up to 100 but to 98. 
And what has changed? (Can't recall that anyone changed anything on that) 

I'm not sure about how much information we have to give about it. Because those infos are based on the sequencing method that is used - so people who did the sequencing or are into this topic know about amplicons and for how many of them they have checked etc.. 
But that's only my probably more insight view. Can you maybe pinpoint the bits of information that would help you to understand it better from your point of view?

**Comment by mirifax** [comment]
not relevant any more, on the current reports
